include: package:flutter_lints/flutter.yaml

# This file configures the Dart analyzer for the project. It imports the
# recommended Flutter lints and excludes the `test/` directory from analysis.

linter:
  rules:
    # You can enable/disable rules here. By default we rely on package:flutter_lints
    # to provide sensible defaults for Flutter projects.

analyzer:
  exclude:
    - test/**
